#!/bin/bash
#

bin_dir=/usr/local/bin
home_dir=${HOME}

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cp ${dir}/alacritty/alacritty.yml ${home_dir}/.config/alacritty/alacritty.yml

cp ${dir}/bash/.bashrc ${home_dir}/.bashrc
cp ${dir}/bash/.bash_profile ${home_dir}/.bashprofile

cp ${dir}/bin/* ${bin_dir}/

cp ${dir}/etc/bash.completion.d/complete_tst /etc/bash.completion.d/complete_tst

cp ${dir}/git/.git-commit-template ${home_dir}/.git-commit-template
cp ${dir}/git/.git-completion.bash ${home_dir}/.git-completion.bash
cp ${dir}/git/.gitconfig ${home_dir}/.gitconfig
cp ${dir}/git/.gitignore ${home_dir}/.gitignore
git config --global commit.template ${home_dir}/.git-commit-template

cp ${dir}/vim/.vimrc ${home_dir}/.vimrc

cp ${dir}/zsh/.zshrc ${home_dir}/.zshrc
